title: 小柏部落格
name: "小柏的Blog"
description: "小柏的Blog，记录技术上遇到的问题，生活中的所思所想"

# global
url: http://zhengbowei.github.io/blog
# post_img: /public/imgs/posts/
post_img: /blog/public/imgs/posts/

# markdown: rdiscount
permalink: /:year/:month/:day/:title
pygment: true

# server options
port: 8888
baseurl: /blog
# baseurl: 

# plugins
gems: ["jekyll-paginate"]

exclude: ["node_modules", "package.json", "gulpfile.js"]

paginate: 7
paginate_path: "/page:num"