title: LIVING CHAPLIN
name: "小柏的Blog"
description: "小柏的Blog，记录技术上遇到的问题，生活中的所思所想"

# global
url: http://zhengbowei.github.io/blog
# post_img: /public/imgs/posts/
post_img: /blog/public/imgs/posts/

# markdown: rdiscount
permalink: pretty
pygment: true

# server options
port: 8888
baseurl: /blog

# plugins
gems: ["jekyll-paginate"]

exclude: ["node_modules", "package.json", "gulpfile.js"]

paginate: 7
paginate_path: "/page:num"