title: LIVING CHAPLIN
name: "小柏的Blog"
description: "记录技术上遇到的问题，生活中的所思所想"

# global
url: /blog
post_img: /blog/public/imgs/posts/

# markdown: rdiscount
permalink: pretty
pygment: true

# server options
port: 9527
baseurl: /blog

exclude: ["node_modules", "package.json", "gulpfile.js"]

paginate: 7
paginate_path: "/page:num"